GET http://localhost:4000/api/v1/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDU1NjAyN2E2ZDc2NTgxZThjZjUyOSIsImlhdCI6MTYxNTQyMjU1OSwiZXhwIjoxNjE1NTA4OTU5fQ.vjMRWgKnuwHaxpfdkx9LfLJ6RWyulz2S3fQwrVP0mg4

### get by id
GET http://localhost:4000/api/v1/users/604518a2e0792d275e8b3eff HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDU1NjAyN2E2ZDc2NTgxZThjZjUyOSIsImlhdCI6MTYxNTQyMjU1OSwiZXhwIjoxNjE1NTA4OTU5fQ.vjMRWgKnuwHaxpfdkx9LfLJ6RWyulz2S3fQwrVP0mg4

### Creacion Registro
POST http://localhost:4000/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "ultimo",
  "lastName": "none",
  "email": "swoddfdffdfrd@gmail.com",
  "password": "123456"
}

### Login
POST http://localhost:4000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "swoddfdffdfrd@gmail.com",
  "password": "123456"
}

###update
PUT http://localhost:4000/api/v1/users/604518a2e0792d275e8b3eff HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDU1NjAyN2E2ZDc2NTgxZThjZjUyOSIsImlhdCI6MTYxNTQyMjU1OSwiZXhwIjoxNjE1NTA4OTU5fQ.vjMRWgKnuwHaxpfdkx9LfLJ6RWyulz2S3fQwrVP0mg4

{
  "name": "ultimo",
  "lastName": "none",
  "email": "swoddfdffdfrd@gmail.com",
  "password": "123456"
}

### delete
DELETE http://localhost:4000/api/v1/users/604518a2e0792d275e8b3eff HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDU1NjAyN2E2ZDc2NTgxZThjZjUyOSIsImlhdCI6MTYxNTQyMjU1OSwiZXhwIjoxNjE1NTA4OTU5fQ.vjMRWgKnuwHaxpfdkx9LfLJ6RWyulz2S3fQwrVP0mg4